apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
      name: http
  type: ClusterIP
  selector:
    app: helloworld