name: 'Pipeline - Development - Monitoring'

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GAR_LOCATION: ${{ secrets.GAR_LOCATION }} # TODO: update region of the Artifact Registry
  GKE_CLUSTER:  ${{ secrets.GKE_CLUSTER }}    # TODO: update to cluster name
  GKE_ZONE:  ${{ secrets.GKE_ZONE }}   # TODO: update to cluster zone
  DEPLOYMENT_NAME: app # TODO: update to deployment name
  REPOSITORY: "repo" # TODO: update to Artifact Registry docker repository 
  IMAGE: app:1.0

on: workflow_dispatch
  #push:
  #  branches:
  #  - "main"
  #pull_request:

permissions:
  contents: read
  id-token: 'write'

jobs:
  monitoring:
    name: 'Pipeline - Dev - Prometheus+Grafana'
    runs-on: ubuntu-latest
    environment: development
    
    outputs:
      output1: ${{ steps.nginx.outputs.ip }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:

    - name: 'Prometheus'
      uses: 'deliverybot/helm@master'
      with:
        release: 'prometheus-community/kube-prometheus-stack'
        namespace: 'prometheus'
        chart: 'kube-prometheus-stack'
        token: '${{ github.token }}'
        value-files: >-
          [
            "./monitoring/prometheus.yaml"
          ]
      env:
        KUBECONFIG_FILE: "./kubeconfigfile"
