name: 'Pipeline - Development - Monitoring'

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GAR_LOCATION: ${{ secrets.GAR_LOCATION }} # TODO: update region of the Artifact Registry
  GKE_CLUSTER:  ${{ secrets.GKE_CLUSTER }}    # TODO: update to cluster name
  GKE_ZONE:  ${{ secrets.GKE_ZONE }}   # TODO: update to cluster zone
  DEPLOYMENT_NAME: helloworld # TODO: update to deployment name
  REPOSITORY: "repo" # TODO: update to Artifact Registry docker repository 
  IMAGE: "helloworld:1.0"

on: workflow_dispatch

permissions:
  contents: read
  id-token: 'write'

jobs:
  deploy:
    name: 'Pipeline - Development - Monitoring'
    runs-on: ubuntu-latest
    environment: development

    outputs:
      output1: ${{ steps.nginx.outputs.ip }}

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        service_account: 'svc-challenge@challenge-01-367100.iam.gserviceaccount.com'
        credentials_json: ${{ secrets.GCLOUD_SVC_KEY }}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: 'Use gcloud CLI'
      run: |-
            gcloud info

    - name: 'Get GKE Credentials'
      run: |-
            gcloud container clusters get-credentials gke-dev-challenge --zone us-central1-a --project challenge-01-367100 >> ./kubeconfigfile

    - name: 'Prometheus'
      uses: 'deliverybot/helm@master'
      with:
        release: 'prometheus-community/kube-prometheus-stack'
        namespace: 'prometheus'
        chart: 'kube-prometheus-stack'
        token: '${{ github.token }}'
        value-files: >-
          [
            "./monitoring/prometheus.yaml"
          ]
      env:
        KUBECONFIG_FILE: "./kubeconfigfile"
